specVersion: 0.2.0
name: parallel-heiko-subql-starter
version: 0.0.4
description: This project can be use as a starting point for parallel-heiko network.
repository: https://github.com/subquery/parallel-heiko-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://parallel-heiko.api.onfinality.io/public-ws
  genesisHash: '0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
